name: oyster-docs

proxy:
  node:
    - oysterdocs.lndo.site

config:
  xdebug: true
  webroot: web/

services:
  node:
    type: node:14
    build: yarn

tooling:
  npm:
    service: node
  npx:
    service: node
  yarn:
    service: node
  doc_start:
    cmd: cd my-website && npx docusaurus start --host 0.0.0.0 --port 80
    service: node
